### ISSUE TITLE
Allow configuring quiet hours

### ISSUE THREAD

**Issue by mitar** [bsc-networks/workshift-website#53]
I think it would be great to show quiet hours on the calendar. So that it is clear when are quiet hours so that member can see when they should maybe not be doing some workshifts.

On the other hand, some workshifts can be done anytime of the day, so there should not be really a limit which hours are displayed on the calendar? (Currently only 6AM-10PM timeslots are shown.)

**Comment by julienfortin** [comment]
Now the workshift manager can change the quiet hours. Just like you can modify the number of required hours I added a new form to modification of quiet hours. I choose to store them in a separate file because I thought that the use of the bd was not super relevant.
The work with the calendar is not done yet. I spent more than 3:30 hours to add this feature, a lot of debugging. I couldn't find out why the form wasn't working. Then I find out it was because the first form was buggy. Having two forms on this page was source of conflict because the first form wasn't correctly closed.I will continue working on the rest of the issue this week.

I was doing unsuccessful test in order to pre-set the value of the form with the quiet hours value but it seems that the "select_time" feature that I am using wasn't accepting the input data that I was using. I will look more on that this week.

**Comment by mlequeux** [comment]
I'll need the quiet hours in the DB as the app will handle multiple units. Or we can also have a filename eg. cloyne_quiet_hours for each unit, but that's probably not the best. We should store the hours in the Unit model that I just made, so we can make sure each unit has easily configurable quiet hours and the design is Cool !.

**Comment by mitar** [comment]
No, please no file storage. Let's just use database for everything. :-) Easier to backup and migrate and everything.

**Comment by julienfortin** [comment]
@mlequeux I will work on your branch to comply to the unit table in the DB. I will just add 2 new columns "quiet_hours_start" & "quiet_hours_end".
I am doing that this afternoon if it's okay for you.

**Comment by brianashpugh** [comment]
looks like this never got done. i'll move it to the db. far as putting quiet hours on the schedule, i'll check it out as part of a larger sweep on the scheduling system + view.

**Comment by mitar** [comment]
OK. So this is per house.

**Comment by brianashpugh** [comment]
quiet hours is ready less the scheduling aspect in my previous comment
