### ISSUE TITLE
need a tab to display workshift policy

### ISSUE THREAD

**Issue by mwaliman** [bsc-networks/workshift-website#65]
Only the WM should be able to edit this

**Comment by mitar** [comment]
That is probably per unit, no?

**Comment by mwaliman** [comment]
yup

**Comment by julienfortin** [comment]
Not sure to understand the issue can you please describe the feature that you'd like?

**Comment by mwaliman** [comment]
I just need another page to display a text document.

also is any progress being done on 60 and 63?

**Comment by julienfortin** [comment]
I will work on 60 & 63 this weekend. I am about to send a half week report.

**Comment by mitar** [comment]
In which format will you have the policy? Markdown? WYSIWYG HTML editor?

**Comment by mwaliman** [comment]
??? .rtf ?

**Comment by mitar** [comment]
So this issue is that there should be a tab where workshift manager can put in a custom static content, describing the policy.

The question is in which format is the workshift manager required to enter this policy. Maybe we should just have a WYSIWYG HTML so that the can copy-paste in from Word or somewhere?

(I assume workshift policy needs things like headings and lists. If it is just pure text, then it can be just a textbox.)

**Comment by mwaliman** [comment]
i don't know what that is, but yes, formatting would be nice

**Comment by post-l** [comment]
Added with commit 8df499b4249736d757a9da197a229d0dd9c9791a

**Comment by post-l** [comment]
![image](https://cloud.githubusercontent.com/assets/3951996/9085110/ce46aa5e-3b2e-11e5-8306-e16867fd1c59.png)
![image](https://cloud.githubusercontent.com/assets/3951996/9085115/d061790e-3b2e-11e5-882e-a546af1f414c.png)
